[project]
name = "stopwatchtk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datetime>=5.5",
    "loguru>=0.7.3",
    "pygame>=2.6.1",
]
